### ISSUE TITLE
Recording on an external SSD

### ISSUE THREAD

**Issue by juliuskoskela** [nordic-dev-net/hydrophonitor#10]
## Overview

Implement recording on a separate SSD attached via USB.

- Should be able to handle device irrespective of UUID
- Should prefer external SSD without any configuration if it is attached (or maybe we add this to the CLI?).

**Comment by satukoskinen** [comment]
Some instruction on automatic SSD mounting on the RPi: https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-automatic-mounting
