### ISSUE TITLE
Implement depth-recorder module

### ISSUE THREAD

**Issue by juliuskoskela** [nordic-dev-net/hydrophonitor#22]
## Overview

- Define depth logging as a systemd service.

**Comment by satukoskinen** [comment]
Consider rewriting in Rust, using crates embedded-hal and ads1x1x:

https://github.com/eldruin/ads1x1x-rs

https://blog.eldruin.com/ads1x1x-analog-to-digital-converter-driver-in-rust/

https://github.com/rust-embedded/embedded-hal
