### ISSUE TITLE
Collaboration - Rust programming - University project

### ISSUE THREAD

**Issue by Danielprobst22** [nordic-dev-net/hydrophonitor#31]
Hey guys,
I'm a computer science master's student living in Germany.
In the context of our degree we have to complete a hands on project and I would love to work with Rust.
I saw Julius' post on reddit and your project seems really cool.
I tried to send a private message to Julius on reddit but I'm not sure if it got through.
I wanted to ask if there are any topics within your project that might be suitable for a group of 2-5 students to work on for one semester (starting now and running until mid-february).
I would be thrilled if a collaboration would be possible.
Cheers, Daniel

**Comment by juliuskoskela** [comment]
Hey Daniel!

Thrilled to have you interested in our project. Please reach out to me via email at me@juliuskoskela.dev and we can discuss if we have something interesting for you guys.
